import React,{useState} from 'react';
import {ArrowRight,Menu,X,CheckCircle2,Mail,ChevronRight} from 'lucide-react';

const enc=s=>'/images/'+encodeURIComponent(s);
const services=[
 ['Digital Transformation','Turning change into a competitive advantage, not a disruption.','Digital transformation.jpg','Digital maturity assessments and transformation roadmaps; legacy modernization; process redesign; change readiness; vendor-neutral technology guidance.'],
 ['Technology & IT','IT strategy built for the business it serves, not the other way around.','Technology and IT.jpg','IT strategy and roadmaps; enterprise architecture; cloud strategy; governance and cost optimization; cybersecurity posture and risk prioritization.'],
 ['Telecom Consulting','Deep operator experience applied to network, commercial, and regulatory strategy.','Telecom consulting.jpg','Network and infrastructure strategy; regulatory and spectrum support; pricing and retention; OSS/BSS transformation; 5G and fiber rollout strategy.'],
 ['Infrastructure Projects','Advisory across the full lifecycle of large capital projects.','Infrastructure projects.jpg','Feasibility and business cases; project structuring; procurement; PMO setup; delivery oversight, risk management and stakeholder coordination.'],
 ['Supply Chain & Operations','Operational resilience and efficiency engineered into how the business runs.','Supply chain and ops.jpg','Network design; demand and inventory planning; procurement and supplier risk; lean process redesign; logistics and distribution strategy.'],
 ['Customer Experience','Experience strategy that shows up in retention and revenue.','Customer experience.jpg','Journey mapping; omnichannel strategy; CRM/contact-center selection; voice-of-customer programs; frontline training and service culture.'],
 ['Training & Capacity Building','Building the internal capability to sustain change after we leave.','Training and capacity.jpg','Leadership development; technical upskilling; change champions; competency frameworks; knowledge transfer and documentation.']
];
const industries=[['Telecom','Telecom industry.jpg'],['Finance','Finance industry.jpg'],['Technology','Technology industry.jpg'],['Public Sector','Public sector.jpg'],['Retail','Retail industry.jpg'],['Manufacturing','Manufacturing.jpg'],['Infrastructure','Infrastructure industry.jpg'],['Healthcare','Healthcare industry.jpg']];
const nav=[['Services','/services'],['Industries','/industries'],['About','/about'],['Approach','/approach'],['Contact','/contact']];

function Header(){const [open,setOpen]=useState(false);return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/15 bg-slate-950/95 text-white backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6"><a href="/" className="flex items-center gap-3"><img src={enc('Exelup Logo.jpg')} className="h-12 w-12 rounded-xl bg-white object-contain p-1"/><span className="text-2xl font-black tracking-tight">exelup</span></a><nav className="hidden gap-8 lg:flex">{nav.map(([n,p])=><a key={p} href={p} className="text-sm font-semibold text-white/80 hover:text-cyan-300">{n}</a>)}</nav><a href="/contact" className="hidden rounded-full bg-cyan-400 px-5 py-3 text-sm font-extrabold text-slate-950 lg:block">Start a conversation</a><button className="lg:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-white/10 px-6 py-5 lg:hidden">{nav.map(([n,p])=><a key={p} href={p} className="block py-3 font-semibold">{n}</a>)}</div>}</header>}
function Footer(){return <footer className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-16 md:grid-cols-2"><div className="flex gap-4"><img src={enc('Exelup Logo.jpg')} className="h-14 w-14 rounded-xl bg-white object-contain p-1"/><div><div className="text-3xl font-black">exelup</div><p className="mt-2 max-w-md text-slate-400">Strategic advisory and management consulting for organizations navigating complex transformation.</p></div></div><div className="grid grid-cols-2 gap-4 text-sm">{nav.map(([n,p])=><a className="text-slate-300 hover:text-cyan-300" href={p} key={p}>{n}</a>)}</div></div><div className="border-t border-white/10 px-6 py-6 text-center text-xs text-slate-500">© 2026 exelup. All rights reserved.</div></footer>}
const Eyebrow=({children})=><p className="mb-5 text-xs font-black uppercase tracking-[.32em] text-cyan-600">{children}</p>;
function PageHero({eyebrow,title,text,img}){return <section className="relative min-h-[520px] overflow-hidden bg-slate-950 pt-20 text-white"><img src={enc(img)} className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/80 to-transparent"/><div className="relative mx-auto flex min-h-[440px] max-w-7xl items-center px-6"><div className="max-w-4xl"><p className="mb-5 font-bold uppercase tracking-[.28em] text-cyan-300">{eyebrow}</p><h1 className="text-5xl font-black tracking-tight sm:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-xl leading-8 text-slate-200">{text}</p></div></div></section>}
function Home(){return <><section className="relative min-h-[780px] overflow-hidden bg-slate-950 text-white"><img src={enc('Strategic advisory.jpg')} className="absolute inset-0 h-full w-full object-cover opacity-40"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/80 to-slate-950/20"/><div className="relative mx-auto flex min-h-[780px] max-w-7xl items-center px-6 pt-20"><div className="max-w-4xl py-24"><div className="mb-8 flex items-center gap-4"><img src={enc('Exelup Logo.jpg')} className="h-20 w-20 rounded-2xl bg-white object-contain p-2 shadow-xl"/><span className="text-3xl font-black">exelup</span></div><p className="mb-6 font-bold uppercase tracking-[.28em] text-cyan-300">Strategic advisory & management consulting</p><h1 className="text-5xl font-black leading-[.98] tracking-tight sm:text-6xl lg:text-8xl">Where strategy<br/><span className="text-cyan-300">meets execution.</span></h1><p className="mt-8 max-w-2xl text-xl leading-8 text-slate-200">We help leadership teams turn ambitious strategy into systems, operations, and measurable results — staying engaged from decision through delivery.</p><div className="mt-10 flex flex-wrap gap-4"><a href="/services" className="inline-flex items-center gap-2 rounded-full bg-cyan-400 px-7 py-4 font-extrabold text-slate-950">Explore our services <ArrowRight size={18}/></a><a href="/about" className="rounded-full border border-white/40 px-7 py-4 font-bold">About exelup</a></div></div></div></section><section className="bg-cyan-400"><div className="mx-auto grid max-w-7xl gap-px bg-slate-900/15 md:grid-cols-3">{['Independent, vendor-neutral advice','Senior expertise through delivery','Outcomes defined from day one'].map((x,i)=><div className="flex items-center gap-3 bg-cyan-400 p-7 font-extrabold" key={x}><span className="text-2xl">0{i+1}</span>{x}</div>)}</div></section><section className="mx-auto max-w-7xl px-6 py-28"><Eyebrow>What we do</Eyebrow><h2 className="max-w-3xl text-4xl font-black sm:text-6xl">Transformation that holds up in operation.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{services.slice(0,3).map(([t,d,img])=><a href="/services" key={t} className="group relative min-h-[340px] overflow-hidden rounded-3xl"><img src={enc(img)} className="absolute inset-0 h-full w-full object-cover transition group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 to-transparent"/><div className="absolute bottom-0 p-7 text-white"><h3 className="text-2xl font-black">{t}</h3><p className="mt-2 text-white/75">{d}</p></div></a>)}</div><a href="/services" className="mt-8 inline-flex items-center gap-2 font-black text-cyan-700">View all services <ArrowRight size={18}/></a></section></>}
function Services(){return <><PageHero eyebrow="What we do" title="Services built for execution." text="Connected advisory, technology and operational capabilities that move organizations from strategic intent to sustainable results." img="Digital transformation.jpg"/><section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-6 md:grid-cols-2">{services.map(([t,d,img,detail],i)=><article key={t} className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><img src={enc(img)} className="h-64 w-full object-cover"/><div className="p-8"><span className="text-xs font-black text-cyan-600">0{i+1}</span><h2 className="mt-2 text-3xl font-black">{t}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{d}</p><p className="mt-4 leading-7 text-slate-600"><strong>What we do:</strong> {detail}</p></div></article>)}</div></section></>}
function Industries(){return <><PageHero eyebrow="Industries" title="Sector depth. Cross-industry perspective." text="We bring sector context together with lessons learned across industries, helping clients solve complex transformation challenges without losing sight of operational realities." img="industries.jpg"/><section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{industries.map(([t,img])=><article key={t} className="group relative aspect-[4/3] overflow-hidden rounded-3xl"><img src={enc(img)} className="h-full w-full object-cover transition group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 to-transparent"/><h2 className="absolute bottom-6 left-6 text-2xl font-black text-white">{t}</h2></article>)}</div></section></>}
function About(){return <><PageHero eyebrow="About exelup" title="Advice that stays through delivery." text="We were built to close the gap between strategy and implementation." img=" team.jpg"/><section className="mx-auto grid max-w-7xl gap-14 px-6 py-24 lg:grid-cols-2 lg:items-center"><img src={enc('Why choose us.jpg')} className="min-h-[480px] w-full rounded-[2rem] object-cover"/><div><Eyebrow>Who we are</Eyebrow><h2 className="text-4xl font-black sm:text-5xl">Transformation only matters if it works in operation.</h2><p className="mt-6 text-lg leading-8 text-slate-600">exelup is a strategic advisory and management consulting firm combining senior advisory judgment, technical depth and hands-on delivery. We stay engaged from decision through implementation rather than handing off a slide deck and walking away.</p><div className="mt-8 space-y-4">{['Senior advisors with real operating experience','Independent recommendations without vendor incentives','Strategy, technology and operations considered together'].map(x=><div className="flex gap-3 font-bold" key={x}><CheckCircle2 className="text-cyan-600"/>{x}</div>)}</div></div></section><section className="bg-slate-100 py-24"><div className="mx-auto grid max-w-7xl gap-5 px-6 md:grid-cols-3">{[['Our Mission','Turning digital ambition into measurable operational results.','Our mission.jpg'],['Our Vision','To be the advisory partner organizations turn to first when strategy has to become reality.','Our vision.jpg'],['Core Values','Excellence, integrity, partnership, impact, and accountability shape every engagement.','Core values.jpg']].map(([t,d,img])=><article className="overflow-hidden rounded-3xl bg-white" key={t}><img src={enc(img)} className="h-56 w-full object-cover"/><div className="p-7"><h3 className="text-2xl font-black">{t}</h3><p className="mt-3 leading-7 text-slate-600">{d}</p></div></article>)}</div></section></>}
function Approach(){let steps=[['01','Discover','Understand how the business actually operates today.'],['02','Design','Build recommendations around your real constraints and goals.'],['03','Deliver','Work alongside your teams through implementation.'],['04','Sustain','Transfer the capability so results continue after we leave.']];return <><PageHero eyebrow="Our approach" title="From insight to sustained impact." text="A consistent delivery method adapted to your organization, priorities and operating context." img="Our approach.jpg"/><section className="mx-auto max-w-5xl px-6 py-24">{steps.map(([n,t,d])=><div className="grid grid-cols-[70px_1fr_auto] items-center border-t border-slate-200 py-9" key={n}><span className="text-xl font-black text-cyan-600">{n}</span><div><h2 className="text-3xl font-black">{t}</h2><p className="mt-2 text-lg text-slate-600">{d}</p></div><ChevronRight/></div>)}</section></>}
function Contact(){return <><PageHero eyebrow="Contact" title="Let's build what comes next." text="Tell us what you are trying to change, improve or deliver. We'll start with the problem, not a pre-packaged solution." img="Partnership.jpg"/><section className="mx-auto max-w-5xl px-6 py-24"><div className="rounded-[2rem] bg-slate-950 p-10 text-white sm:p-14"><Eyebrow>Start a conversation</Eyebrow><h2 className="text-4xl font-black">Talk with ExelUp.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">For consulting, partnerships, transformation programs and strategic advisory engagements, contact our team directly.</p><a href="mailto:info@exelup.com" className="mt-9 inline-flex items-center gap-3 rounded-full bg-cyan-400 px-7 py-4 font-black text-slate-950"><Mail size={19}/> info@exelup.com</a></div></section></>}
function App(){const path=window.location.pathname.replace(/\/$/,'')||'/';let page=path==='/services'?<Services/>:path==='/industries'?<Industries/>:path==='/about'?<About/>:path==='/approach'?<Approach/>:path==='/contact'?<Contact/>:<Home/>;return <main className="bg-white text-slate-950 selection:bg-cyan-200"><Header/>{page}<Footer/></main>}
export default App;
